"""
Add CSE and NEO Exchange tickers to universe_full.json.
CSE tickers use .CN suffix in yfinance.
NEO tickers use .NE suffix in yfinance.
"""

import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
UNIVERSE_FILE = os.path.join(DATA_DIR, 'universe_full.json')

# CSE tickers scraped from stockanalysis.com/list/canadian-securities-exchange/
# These are the raw symbols (without .CN suffix)
CSE_TICKERS_RAW = [
    ("HG", "HydroGraph Clean Power Inc."),
    ("GTII", "Green Thumb Industries Inc."),
    ("TRUL", "Trulieve Cannabis Corp."),
    ("DRUG", "Bright Minds Biosciences Inc."),
    ("VREO", "Vireo Growth Inc."),
    ("SNDL", "SNDL Inc."),
    ("ACT", "Aduro Clean Technologies Inc."),
    ("CL", "Cresco Labs Inc."),
    ("ACM", "Allied Critical Metals Inc."),
    ("RECE", "Resource Centrix Holdings, Inc."),
    ("DPRO", "Draganfly Inc."),
    ("AIRX", "Redwood AI Corp."),
    ("HBFG", "Happy Belly Food Group Inc."),
    ("PHOS", "First Phosphate Corp."),
    ("MAXX", "Max Power Mining Corp."),
    ("KUYA", "Kuya Silver Corporation"),
    ("TUNG", "American Tungsten Corp."),
    ("APXC", "Apex Critical Metals Corp."),
    ("AGC", "Avanti Gold Corp."),
    ("URL", "NameSilo Technologies Corp."),
    ("JUSH", "Jushi Holdings Inc."),
    ("EVR", "Evolve Royalties Ltd"),
    ("NOM", "Norsemont Mining Inc."),
    ("CCI", "Canadian Copper Inc."),
    ("ATMY", "Antimony Resources Corp."),
    ("BLLG", "Blue Lagoon Resources Inc."),
    ("LEO", "Lion Copper and Gold Corp."),
    ("NVRS", "Noveris Health Sciences Inc."),
    ("AMQ", "Abitibi Metals Corp."),
    ("SANU", "Sanu Gold Corp."),
    ("MSM", "Metalsource Mining Inc."),
    ("GRIN", "Grown Rogue International Inc."),
    ("QIMC", "Quebec Innovative Materials Corp."),
    ("ARS", "Ares Strategic Mining Inc."),
    ("RAIL", "Railtown AI Technologies Inc."),
    ("PSIL", "Pacifica Silver Corp."),
    ("CUAU", "Forte Minerals Corp."),
    ("BLO", "Cannabix Technologies Inc."),
    ("NRED", "NovaRed Mining Inc."),
    ("METX", "ME Therapeutics Holdings Inc."),
    ("UG", "Upside Gold Corp."),
    ("SPAI", "Sparc Al Inc."),
    ("RISE", "Rise Gold Corp."),
    ("FOX", "Fox River Resources Corporation"),
    ("PLTH", "Planet 13 Holdings Inc."),
    ("CRTL", "Critical One Energy Inc."),
    ("VEXT", "Vext Science, Inc."),
    ("EMPS", "EMP Metals Corp."),
    ("AIDR", "Rocket Doctor AI Inc."),
    ("VST", "Victory Square Technologies Inc."),
    ("MMET", "Miata Metals Corp."),
    ("STCU", "Star Copper Corp."),
    ("LFLR", "LaFleur Minerals Inc."),
    ("BNXT", "BioNxt Solutions Inc."),
    ("VIVI", "TempraMed Technologies Ltd."),
    ("YMC", "Yukon Metals Corp."),
    ("PXI", "Planet Ventures Inc."),
    ("ISTK", "Intellistake Technologies Corp."),
    ("TOC", "Tocvan Ventures Corp."),
    ("WUC", "Western Uranium & Vanadium Corp."),
    ("ESAU", "ESGold Corp."),
    ("BUX", "Biomark Diagnostics Inc."),
    ("MLM", "McFarlane Lake Mining Limited"),
    ("HODL", "Sol Strategies Inc."),
    ("NUR", "Nuran Wireless Inc."),
    ("M", "Myriad Uranium Corp."),
    ("LEEF", "Leef Brands Inc."),
    ("GRBM", "Green Bridge Metals Corporation"),
    ("GTCH", "Getchell Gold Corp."),
    ("TICO", "Talent Infinity Resource Developments Inc."),
    ("FRG", "Forge Resources Corp."),
    ("CTTT", "Critical Infrastructure Technologies Ltd."),
    ("TN", "Tartisan Nickel Corp."),
    ("ICS", "Integrated Cyber Solutions Inc."),
    ("CYBT", "Cybeats Technologies Corp."),
    ("USGD", "American Pacific Mining Corp."),
    ("HTRC", "High Tide Resources Corp."),
    ("WBGD", "Waraba Gold Limited"),
    ("QESS", "Aegis Critical Energy Defence Corp."),
    ("JSDA", "Jones Soda Co."),
    ("MAXM", "Maxus Mining Inc."),
    ("PAU", "Provenance Gold Corp."),
    ("NAHF", "North America Home Finance Inc."),
    ("FAT", "Foremost Clean Energy Ltd."),
    ("CACR", "The Canadian Chrome Company Inc."),
    ("FOMO", "Formation Metals Inc."),
    ("BAR", "Barranco Gold Mining Corp."),
    ("CXXI", "C21 Investments Inc."),
    ("MILI", "Military Metals Corp."),
    ("DTC", "Defence Therapeutics Inc."),
    ("NPRA", "Nepra Foods Inc."),
    ("HWG", "Headwater Gold Inc."),
    ("MRMD", "MariMed Inc."),
    ("NEXX", "Nexcel Metals Corp."),
    ("SONA", "Sona Nanotech Inc."),
    ("IAN", "iAnthus Capital Holdings, Inc."),
    ("HEAT", "Hillcrest Energy Technologies Ltd."),
    ("SCU", "Sankamap Metals Inc."),
    ("ERTH", "Replenish Nutrients Holding Corp."),
    ("KING", "King Global Ventures Inc."),
    ("PRNC", "Prince Silver Corp."),
    ("CUPR", "Super Copper Corp."),
    ("AUOZ", "Emperor Metals Inc."),
    ("NBRK", "New Break Resources Ltd."),
    ("MTTA", "Meta Critical Minerals Inc."),
    ("VRDN", "Viridian Metals Inc."),
    ("MVMD", "Mountain Valley MD Holdings Inc."),
    ("TELI", "Telescope Innovations Corp."),
    ("SEAS", "Deep Sea Minerals Corp."),
    ("NICO", "Class 1 Nickel and Technologies Limited"),
    ("API", "Appia Rare Earths & Uranium Corp."),
    ("EMET", "Canamera Energy Metals Corp."),
    ("IRV", "Irving Resources Inc."),
    ("NTAR", "Nextech3D.AI Corporation"),
    ("AUCU", "Inflection Resources Ltd."),
    ("INNO", "InnoCan Pharma Corporation"),
    ("CSR", "Copper Standard Resources Inc."),
    ("LGHT", "Lighthouse Gold Inc."),
    ("OPTI", "Optimi Health Corp."),
    ("QIM", "Quimbaya Gold Inc."),
    ("SLV", "Silver Dollar Resources Inc."),
    ("SXTY", "Sixty North Gold Mining Ltd."),
    ("NOP", "Nevada Organic Phosphate Inc."),
    ("BMT", "Bahia Metals Corp."),
    ("GOAT", "GOAT Industries Ltd."),
    ("EONX", "EonX Technologies Inc."),
    ("VLTA", "Volta Metals Ltd."),
    ("RI", "Royalties Inc."),
    ("QNTM", "Quantum BioPharma Ltd."),
    ("KBX", "Kobrea Exploration Corp."),
    ("GXP", "Greenridge Exploration Inc."),
    ("LOBE", "Lobe Sciences Ltd."),
    ("HYTN", "HYTN Innovations Inc."),
    ("PSE", "Pasinex Resources Limited"),
    ("NTMC", "Neotech Metals Corp."),
    ("FNAU", "Four Nines Gold Inc."),
    ("ICG", "ICG Silver & Gold Ltd."),
    ("RUU", "Refined Energy Corp."),
    ("CUPA", "Cupani Metals Corp."),
    ("CC", "Core Silver Corp."),
    ("DRC", "DRC Gold Corp."),
    ("ULTH", "United Lithium Corp."),
    ("TEX", "Targa Exploration Corp."),
    ("CXC", "CMX Gold & Silver Corp."),
    ("CANU", "Canadian Uranium Corp."),
    ("BAC", "BacTech Environmental Corporation"),
    ("GWAY", "Greenway Greenhouse Cannabis Corporation"),
    ("WSR", "Western Star Resources Inc."),
    ("FTEL", "First Tellurium Corp."),
    ("MRM", "Micromem Technologies Inc."),
    ("WG", "Westward Gold Inc."),
    ("INTG", "Integral Metals Corp."),
    ("NEXU", "Nexus Uranium Corp."),
    ("LECR", "Leocor Mining Inc."),
    ("SLA", "Silver Acadia Exploration Inc."),
    ("BLST", "Blast Resources Inc."),
    ("NIOB", "North American Niobium and Critical Minerals Corp."),
    ("RVV", "Revive Therapeutics Ltd."),
    ("UE", "Urano Energy Corp."),
    ("PAI", "Predictiv AI Inc."),
    ("AVE", "Aventis Energy Inc."),
    ("GOH", "GoldHaven Resources Corp."),
    ("BATX", "Battery X Metals Inc."),
    ("SKUR", "Sekur Private Data Ltd."),
    ("ZIGY", "Stardust Metal Corp."),
    ("NINE", "Nine Mile Metals Ltd."),
    ("IZO", "Izotropic Corporation"),
    ("GPK", "Grand Peak Capital Corp."),
    ("GLM", "Golden Lake Exploration Inc."),
    ("CFE", "Cartier Silver Corporation"),
    ("RKL", "Rockland Resources Ltd."),
    ("ATHA", "Athena Gold Corporation"),
    ("MERC", "Mercado Minerals Ltd."),
    ("GRUN", "Gold Runner Exploration Inc."),
    ("PLAS", "PlasCred Circular Innovations Inc."),
    ("ARGO", "Argo Graphene Solutions Corp."),
    ("EAGL", "EagleOne Metals Corporation"),
    ("HUNT", "Gold Hunter Resources Inc."),
    ("REVV", "ReVolve Renewable Power Corp."),
    ("PNRG", "Pan American Energy Corp."),
    ("PMAX", "Powermax Minerals Inc."),
    ("PMC", "Peloton Minerals Corporation"),
    ("REDC", "Red Canyon Resources Ltd."),
    ("MEO", "Cameo Resources Inc."),
    ("LUX", "Newlox Gold Ventures Corp."),
    ("HHE", "First Atlas Resources Corp."),
    ("DOSE", "Rapid Dose Therapeutics Corp."),
    ("RWB", "Red White & Bloom Brands Inc."),
    ("SX", "St-Georges Eco-Mining Corp."),
    ("SHRC", "Sharc International Systems Inc."),
    ("DEMC", "Discovery Energy Metals Corp."),
    ("BLAB", "Britannia Life Sciences Inc."),
    ("FFF", "55 North Mining Inc."),
    ("TTX", "Tantalex Lithium Resources Corp."),
    ("CQX", "Copper Quest Exploration Inc."),
    ("TMAS", "Temas Resources Corp."),
    ("UUU", "Vanguard Mining Corp."),
    ("XRI", "Xcite Uranium Inc."),
    ("ZEUS", "Zeus North America Mining Corp."),
    ("CAPR", "Caprock Mining Corp."),
    ("TRIP", "Red Light Holland Corp."),
    ("HAMR", "Silver Hammer Mining Corp."),
    ("ERKA", "Eureka Lithium Corp."),
    ("STAR", "Starmet Ventures Inc."),
    ("FNI", "Fathom Nickel Inc."),
    ("PREV", "PreveCeutical Medical Inc."),
    ("RGX", "Regenx Tech Corp."),
    ("SRS", "Sorrento Resources Ltd."),
    ("BOOM", "Galloper Gold Corp."),
    ("EPG", "Epic Gold Corp."),
    ("FLM", "First Lithium Minerals Corp."),
    ("RSH", "Rush Rare Metals Corp."),
    ("HM", "HM Exploration Corp."),
    ("GCC", "Golden Cariboo Resources Ltd."),
    ("SRAN", "Sranan Gold Corp."),
    ("BOLT", "Bolt Metals Corp."),
    ("NIX", "NorthX Nickel Corp."),
    ("BETR", "BetterLife Pharma Inc."),
    ("MDMA", "Pharmala Biotech Holdings Inc."),
    ("SUU", "Strathmore Plus Uranium Corp."),
    ("AFX", "Arctic Fox Lithium Corp."),
    ("GFT", "Grafton Resources Inc."),
    ("STGX", "StrategX Elements Corp."),
    ("ATC", "ATERRA Metals Inc."),
    ("CRCL", "Corcel Exploration Inc."),
    ("WDGY", "Wedgemount Resources Corp."),
    ("FNX", "FNX Inc."),
    ("SCM", "Steadright Critical Minerals Inc."),
    ("IDK", "ThreeD Capital Inc."),
    ("VSBY", "VSBLTY Groupe Technologies Corp."),
    ("NATO", "North Atlantic Titanium Corp."),
    ("BFG", "Giant Mining Corp."),
    ("GLOW", "Glow Lifetech Corp."),
    ("GGR", "Golden Goose Resources Corp."),
    ("RGR", "Rio Grande Resources Ltd."),
    ("LIBR", "Libra Energy Materials Inc."),
    ("AUMC", "Auric Minerals Corp."),
    ("OILS", "Nextleaf Solutions Ltd."),
    ("RFR", "Renforth Resources Inc."),
    ("ALMA", "Alma Gold Inc."),
    ("PDO", "PUDO Inc."),
    ("PRR", "Prospect Ridge Resources Corp."),
    ("BDR", "Bird River Resources Inc."),
    ("KOG", "KO Gold Inc."),
    ("SPRK", "Spark Energy Minerals Inc."),
    ("NUE", "NU E Power Corp."),
    ("AIML", "AI/ML Innovations Inc."),
    ("SNA", "Star Navigation Systems Group Ltd."),
    ("NSG", "Northstar Gold Corp."),
    ("NLR", "Northern Lights Resources Corp."),
    ("FNQ", "Fineqia International Inc."),
    ("BTC", "Bluesky Digital Assets Corp."),
    ("PKK", "Tenet Fintech Group Inc."),
    ("PURR", "Panther Minerals Inc."),
    ("SL", "Super Lithium Corp."),
    ("NATN", "Nation Gold Corp."),
    ("PRIZ", "Prismo Metals Inc."),
    ("GURN", "Global Uranium Corp."),
    ("NWI", "Nuinsco Resources Limited"),
    ("HZ", "Hertz Energy Inc."),
    ("CNCO", "Core Nickel Corp."),
    ("BRS", "BRS Resources Ltd."),
    ("LUXX", "Luxxfolio Holdings Inc."),
    ("HML", "Heritage Mining Ltd."),
    ("MBIO", "MindBio Therapeutics Corp."),
    ("OMGA", "Omega Pacific Resources Inc."),
    ("OWLI", "One World Lithium Inc."),
    ("CLC", "Christina Lake Cannabis Corp."),
    ("MIRL", "Minera IRL Limited"),
    ("PBIT", "POSaBIT Systems Corporation"),
    ("COMT", "Collective Metals Inc."),
    ("AUEX", "Advanced Gold Exploration Inc."),
    ("TMIN", "Teako Minerals Corp."),
    ("SUR", "Surface Metals Inc."),
    ("SASQ", "Sasquatch Resources Corp."),
    ("UCM", "United Critical Minerals Corp."),
    ("GSRI", "Golden Shield Resources Inc."),
    ("TCEC", "Terra Clean Energy Corp."),
    ("VRTX", "Vortex Energy Corp."),
    ("PHRM", "PharmaTher Holdings Ltd."),
    ("SURE", "SureNano Science Ltd."),
    ("GMR", "Gelum Resources Ltd."),
    ("TAUR", "Taurus Gold Corp."),
    ("BGLD", "Boreal Gold Inc."),
    ("SCYB", "Scryb Inc."),
    ("SE", "Sweet Earth Holdings Corporation"),
    ("ARQ", "Argo Gold Inc."),
    ("GPO", "Gold Port Corporation"),
    ("MEDA", "Medaro Mining Corp."),
    ("MLKM", "Mayo Lake Minerals Inc."),
    ("CGII", "CleanGo Innovations Inc."),
    ("TCF", "Trillion Energy International Inc."),
    ("GCP", "Golcap Resources Corp."),
    ("GMC", "Germanium Mining Corp."),
    ("ETR", "Etruscus Resources Corp."),
    ("PSYC", "Psyched Wellness Ltd."),
    ("MCL", "McLaren Resources Inc."),
    ("ARGL", "Argyle Resources Corp."),
    ("TAAT", "TAAT Global Alternatives Inc."),
    ("MOC", "Mosaic Minerals Corp."),
    ("ISP", "Inspiration Mining Corp."),
    ("HLND", "Highland Critical Minerals Corp."),
    ("RAD", "Radial Research Corp."),
    ("GGC", "Generic Gold Corp."),
    ("ORGN", "Origen Resources Inc."),
    ("TGIF", "1933 Industries Inc."),
    ("ELEM", "Element79 Gold Corp."),
    ("AMMP", "AmmPower Corp."),
    ("HYPE", "Hyper Bit Technologies Ltd."),
    ("ARM", "Armada Mercantile Ltd."),
    ("BBM", "Blueberries Medical Corp."),
    ("PGOL", "Patriot Gold Corp."),
    ("CAMP", "Canadian GoldCamps Corp."),
    ("CRUZ", "Cruz Battery Metals Corp."),
    ("MEC", "Mustang Energy Corp."),
    ("TRG", "Tarachi Gold Corp."),
    ("WIFI", "American Aires Inc."),
    ("RXM", "Rockex Mining Corporation"),
    ("ANT", "Anteros Metals Inc."),
    ("QNI", "Quebec Nickel Corp."),
    ("C", "Commodore Metals Corp."),
    ("SK", "Rottenstone Gold Inc."),
    ("WGM", "WestGold Metals Corp."),
    ("TERA", "Terra Balcanica Resources Corp."),
    ("SQX", "Squatex Energy and Resources Inc."),
    ("QCA", "Quinsam Capital Corporation"),
    ("LINE", "Linear Minerals Corp."),
    ("BEAU", "Beaumont Exploration Corp."),
    ("GRUV", "Protium Clean Energy Corp."),
    ("MYR", "Meryllion Resources Corp."),
    ("NT", "Newterra Resources Inc."),
    ("LCR", "Lancaster Resources Inc."),
    ("STK", "Silverstock Metals Inc."),
    ("BSKY", "BluSky Carbon Inc."),
    ("FWM", "Flow Metals Corp."),
    ("GOR", "Goldrea Resources Corp."),
    ("KVM", "Kingsview Minerals Ltd."),
    ("NVR", "North Valley Resources Ltd."),
    ("CRC", "Canter Resources Corp."),
    ("ASEP", "ASEP Medical Holdings Inc."),
    ("MOLT", "Molten Metals Corp"),
    ("CMET", "Clarity Metals Corp."),
    ("CASC", "Cascade Copper Corp."),
    ("AA", "Avventura Resources Ltd."),
    ("STNG", "Stinger Resources Inc."),
    ("PGR", "Planet Green Metals Inc."),
    ("SGRO", "Sierra Grande Minerals Inc."),
    ("BY", "Beyond Minerals Inc."),
    ("MM", "Maximus Metals Inc."),
    ("TRAC", "Traction Uranium Corp."),
    ("ADP", "Adelphi Metals Inc."),
    ("JBR", "James Bay Resources Limited"),
    ("GC", "Goldcana Resources Inc."),
    ("BG", "Big Gold Inc."),
    ("SAND", "Silver Sands Resources Corp."),
    ("NEWD", "Newfoundland Discovery Corp."),
    ("ROBO", "Humanoid Global Holdings Corp."),
    ("AICO", "Generative AI Solutions Corp."),
    ("HODL", "Sol Strategies Inc."),
    ("MILI", "Military Metals Corp."),
    ("WIFI", "American Aires Inc."),
    ("RAIL", "Railtown AI Technologies Inc."),
    ("SPAI", "Sparc Al Inc."),
]

# Known NEO Exchange tickers (use .NE suffix in yfinance)
NEO_TICKERS_RAW = [
    ("MMED", "MindMedicine (MindMed) Inc."),
    ("NUMI", "Numinus Wellness Inc."),
    ("VERY", "VERY Good Food Company Inc."),
    ("LUCK", "Real Luck Group Ltd."),
    ("CBDT", "Empower Clinics Inc."),
    ("GENI", "Genius Brands International Inc."),
    ("HBIT", "Hut 8 Bitcoin ETF"),
    ("BTCC", "Purpose Bitcoin ETF"),
    ("ETHY", "Purpose Ether ETF"),
    ("ETHH", "CI Galaxy Ethereum ETF"),
    ("BTCX", "CI Galaxy Bitcoin ETF"),
    ("DEFI", "Evolve Cryptocurrencies ETF"),
    ("ETC", "Purpose Ether Yield ETF"),
    ("BITI", "BetaPro Inverse Bitcoin ETF"),
    ("FBTC", "Fidelity Advantage Bitcoin ETF"),
    ("QETH", "3iQ CoinShares Ether Staking ETF"),
    ("QBTC", "3iQ CoinShares Bitcoin ETF"),
    ("HISA", "High Interest Savings Account ETF"),
    ("CASH", "Global X High Interest Savings ETF"),
    ("HSAV", "NBI High Interest Savings ETF"),
    ("CBIL", "CIBC Active Investment Grade Corporate Bond ETF"),
    ("EARN", "Evolve Enhanced Yield Bond Fund"),
    ("BASE", "Evolve Global Materials & Mining Enhanced Yield Index ETF"),
    ("LIFE", "Evolve Global Healthcare Enhanced Yield Fund"),
    ("CALL", "Evolve US Banks Enhanced Yield Fund"),
    ("BANK", "Evolve Canadian Banks Enhanced Yield Fund"),
    ("FOOD", "Evolve Global Agriculture Enhanced Yield Fund"),
    ("DATA", "Evolve Cloud Computing Index Fund"),
    ("EDGE", "Evolve Innovation Index Fund"),
    ("HERO", "Evolve E-Gaming Index ETF"),
    ("CARS", "Evolve Automobile Innovation Index Fund"),
    ("CYBR", "Evolve Cyber Security Index Fund"),
    ("BKCH", "Global X Blockchain Index ETF"),
    ("CHPS", "Global X Semiconductor Index ETF"),
    ("RBOT", "Global X Robotics & AI Index ETF"),
    ("EAAI", "Evolve Artificial Intelligence Fund"),
    ("APTS", "Purpose Multi-Asset Real Estate Fund"),
    ("DIVS", "Evolve Active Canadian Preferred Share Fund"),
    ("GXMD", "Global X Medical Device Index ETF"),
    ("GX", "Global X Active Cdn Dividend ETF"),
    ("QQCC", "Global X NASDAQ-100 Covered Call ETF"),
    ("GLCC", "Global X Gold Producer Equity Covered Call ETF"),
    ("BNCC", "Global X Canadian Bank Covered Call ETF"),
    ("USCC", "Global X US Equity Covered Call ETF"),
    ("SPEC", "Purpose Diversified Real Asset Fund"),
    ("UTIL", "Evolve US Utilities Enhanced Yield Fund"),
    ("PREF", "Global X Active Canadian Preferred Share ETF"),
    # Non-ETF NEO listings
    ("NEXE", "NEXE Innovations Inc."),
    ("WLLW", "Willow Biosciences Inc."),
    ("BIGG", "BIGG Digital Assets Inc."),
    ("CSTR", "CarbonStream Inc."),
    ("CULT", "Cult Food Science Corp."),
    ("HELX", "Helix Technologies Inc."),
    ("NBLY", "Neighbourly Pharmacy Inc."),
    ("SOLR", "Solar Alliance Energy Inc."),
    ("NUVG", "Nuvei Corporation"),
]


def build_cse_entries():
    """Build universe entries for CSE tickers."""
    entries = []
    seen = set()
    for symbol, name in CSE_TICKERS_RAW:
        ticker = f"{symbol}.CN"
        if ticker in seen:
            continue
        seen.add(ticker)
        entries.append({
            "ticker": ticker,
            "yf_ticker": ticker,
            "name": name,
            "exchange": "CSE",
            "sector": "Other",
        })
    return entries


def build_neo_entries():
    """Build universe entries for NEO tickers."""
    entries = []
    seen = set()
    for symbol, name in NEO_TICKERS_RAW:
        ticker = f"{symbol}.NE"
        if ticker in seen:
            continue
        seen.add(ticker)
        entries.append({
            "ticker": ticker,
            "yf_ticker": ticker,
            "name": name,
            "exchange": "NEO",
            "sector": "Other",
        })
    return entries


def main():
    # Load existing universe
    with open(UNIVERSE_FILE, 'r') as f:
        universe = json.load(f)

    existing_tickers = {entry['ticker'] for entry in universe}
    print(f"Existing universe: {len(universe)} tickers")

    # Add CSE tickers
    cse_entries = build_cse_entries()
    new_cse = [e for e in cse_entries if e['ticker'] not in existing_tickers]
    print(f"CSE tickers to add: {len(new_cse)} (out of {len(cse_entries)} total, {len(cse_entries) - len(new_cse)} already exist)")

    # Add NEO tickers
    neo_entries = build_neo_entries()
    new_neo = [e for e in neo_entries if e['ticker'] not in existing_tickers]
    print(f"NEO tickers to add: {len(new_neo)} (out of {len(neo_entries)} total, {len(neo_entries) - len(new_neo)} already exist)")

    # Merge
    universe.extend(new_cse)
    universe.extend(new_neo)

    # Sort by ticker
    universe.sort(key=lambda x: x['ticker'])

    # Save
    with open(UNIVERSE_FILE, 'w') as f:
        json.dump(universe, f, indent=2)

    print(f"\nUpdated universe: {len(universe)} tickers")
    print(f"  CSE: {len([u for u in universe if u.get('exchange') == 'CSE'])}")
    print(f"  NEO: {len([u for u in universe if u.get('exchange') == 'NEO'])}")
    print(f"  TSX: {len([u for u in universe if u.get('exchange') == 'TSX'])}")
    print(f"  TSXV: {len([u for u in universe if u.get('exchange') == 'TSXV'])}")


if __name__ == '__main__':
    main()
